version: '2'
services:
  wordpress:
    container_name: wp-hope21
    image: wordpress:latest
    external_links:
      - mariadb:mysql
      - mailhog
    restart: always
    environment:
      WORDPRESS_DB_NAME: hope21
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 1001:80
    networks:
      - local_default
networks:
  local_default:
    external: true
